# Generated by Django 3.2.16 on 2022-11-21 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='desc',
            new_name='descr',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='img',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='name',
            new_name='namet',
        ),
    ]
